import Machel from '../../assets/images/dashbord/machel.png'
import Joannah from '../../assets/images/dashbord/joannah.png'
import Kevin from '../../assets/images/dashbord/kevin.png'

export const emailData = [
    {
        recentEmail: "kevinhard@mail.com",
        recentTitle: "Quotation for the requested products",
        recentImg: Kevin,
        type: 'important',
        time: '24 min ago',
        recentDes: "Ipsmum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        isSnooze: true,
        isRead: true,
        isStar: false,
        attechment: false,
        isPined: true,
        isChecked: false,
        showIcon: false,
    },
    {
        recentEmail: "joanhsitepu@mail.com",
        recentTitle: "Need 10 Smart Phones for our team",
        recentImg: Joannah,
        type: 'important',
        time: 'yesterday,at 11:24,AM',
        recentDes: "Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        isSnooze: true,
        isRead: false,
        isStar: true,
        attechment: true,
        isPined: true,
        isChecked: false,
        showIcon: false,
    },
    {
        recentEmail: "machelgreen@mail.com",
        recentTitle: "Order confirmed",
        recentImg: Machel,
        type: "important",
        time: 'October 25th,2020 08:55PM',
        recentDes: "Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        isSnooze: true,
        isRead: false,
        isStar: true,
        attechment: false,
        isPined: false,
        isChecked: false,
        showIcon: false,
    },
    {
        recentEmail: "kevinhard@mail.com",
        recentTitle: "Quotation for the requested products",
        recentImg: Kevin,
        type: 'social',
        time: '24 min ago',
        recentDes: "Ipsmum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        isSnooze: true,
        isRead: false,
        isStar: true,
        attechment: false,
        isPined: false,
        isChecked: false,
        showIcon: false,
    },
    {
        recentEmail: "joanhsitepu@mail.com",
        recentTitle: "Need 10 Smart Phones for our team",
        recentImg: Joannah,
        type: 'social',
        time: 'yesterday,at 11:24,AM',
        recentDes: "Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        isSnooze: true,
        isRead: false,
        isStar: true,
        attechment: true,
        isPined: false,
        isChecked: false,
        showIcon: false,
    },
    {
        recentEmail: "machelgreen@mail.com",
        recentTitle: "Order confirmed",
        recentImg: Machel,
        type: "social",
        time: 'October 25th,2020 08:55PM',
        recentDes: "Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        isSnooze: true,
        isRead: true,
        isStar: true,
        attechment: true,
        isPined: false,
        isChecked: false,
        showIcon: false,
    },
    {
        recentEmail: "kevinhard@mail.com",
        recentTitle: "Quotation for the requested products",
        recentImg: Kevin,
        type: 'promotion',
        time: '24 min ago',
        recentDes: "Ipsmum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        isSnooze: true,
        isRead: false,
        isStar: false,
        attechment: false,
        isPined: false,
        isChecked: false,
        showIcon: false,
    },
    {
        recentEmail: "joanhsitepu@mail.com",
        recentTitle: "Need 10 Smart Phones for our team",
        recentImg: Joannah,
        type: 'promotion',
        time: 'yesterday,at 11:24,AM',
        recentDes: "Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        isSnooze: true,
        isRead: false,
        isStar: false,
        attechment: false,
        isPined: false,
        isChecked: false,
        showIcon: false,
    },
    {
        recentEmail: "machelgreen@mail.com",
        recentTitle: "Order confirme",
        recentImg: Machel,
        type: "promotion",
        time: 'October 25th,2020 08:55PM',
        recentDes: "Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        isSnooze: true,
        isRead: false,
        isStar: false,
        attechment: false,
        isPined: false,
        isChecked: false,
        showIcon: false,
    }
]